---

- import_tasks: dist_vars.yml

- import_tasks: install.yml

- name: Set boolean method check to all profiles
  set_fact:
    wireguard_profiles_bool_methods: "{{
      wireguard_profiles_bool_methods|default({})|combine({
        item.key: {
          'use_wg_quick': item.value.method == 'wg-quick',
          'use_systemd_networkd': item.value.method == 'systemd-networkd',
          'use_wg_conf_dump': item.value.method == 'wireguard-conf'
        }
      })
    }}"
  with_dict: "{{ wireguard_profiles }}"

- name: Update profiles with boolean methods
  set_fact:
    wireguard_profiles: "{{ wireguard_profiles|combine(wireguard_profiles_bool_methods, recursive=True) }}"

- include_tasks: wg_quick.yml
  vars:
    profile: "{{ item.value }}"
    profile_name: "{{ item.key }}"
  with_dict: "{{ wireguard_profiles }}"
  when: item.value.use_wg_quick

- include_tasks: systemd_networkd.yml
  vars:
    profile: "{{ item.value }}"
    profile_name: "{{ item.key }}"
  with_dict: "{{ wireguard_profiles }}"
  when: item.value.use_systemd_networkd

- include_tasks: wg_conf.yml
  vars:
    profile: "{{ item.value }}"
    profile_name: "{{ item.key }}"
  with_dict: "{{ wireguard_profiles }}"
  when: item.value.use_wg_conf_dump

# vim: set ts=2 sw=2:
